services:
  app:
    build:
      context: .
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL:-http://localhost:3000}
    init: true
    shm_size: "1gb"
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "3000:3000"
    environment:
      FRONTEND_PORT: 3001
    volumes:
      - app-storage:/app/apps/backend/storage

volumes:
  app-storage:
